name: EnhancedFurnace
version: ${project.version}
main: me.architetto.enhancedfurnace.EnhancedFurnace
api-version: 1.16
authors: [ Architetto ]
commands:
  enhancedfurnace:
    description: enhanced furnace
    aliases:
      - enf

permissions:
  enhancedfurnace.add:
    description: add enhanced furnace
    default: op
  enhancedfurnace.remove:
    description: remove enhanced furnace
    default: op
