####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                      EnhancedFurnace                                         | #
# |                                    Made by: Architetto                                       | #
# |                                    SOURCE CODE:  ---                                         | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

anhanced_furnace :
  default_cook_speed: 200
  set_fire_on_burn_probability: 0.2
  custom_cook_speed:
    - 'IRON_ORE,2000'
    - 'GOLD_ORE,3000'
    - 'DIAMOND_ORE,5000'
    - 'ANCIENT_DEBRIS,7000'
  exp_multiplier: 5
  result_multiplier:
    - 'IRON_INGOT,10'
    - 'GOLD_INGOT,5'
    - 'DIAMOND,6'
    - 'NETHERITE_SCRAP,4'


strings:
  prefix: "&8[&l&6En&4F&r&8]&r"

  furnace_added: "Fornace aggiunta correttamente [&e{0}&r]"
  furnace_removed: "Fornace rimossa correttamente [&e{0}&r]"
  success_reload: "File di configurazione ricaricato "

  #ERROR MESSAGES
  err_not_enf: "&cLa fornace indicata non e' una EnhancedFurnace"
  err_is_enf: "&cLa fornace indicata e' già una EnhancedFurnace"
  err_block_not_found: "&cNessun blocco fornace trovato"

  #COMMAND DESCRIPTION
  add_command: "&aRende la fornace targhettata una EnhancedFurnace"
  remove_command: "&aRipristina la fornace targhettata al suo stato classico"
  reload_command: "&aRicarica il file di configurazione"

  #LOG
  enf_break: "Enhanced furnace removed at [&e{0}&r] by &e{1}&r"



