####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                      EnhancedFurnace                                         | #
# |                                    Made by: Architetto                                       | #
# |                                    SOURCE CODE:  ---                                         | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

anhanced_furnace :
  # [default_cook_speed] cook speed for items without custom cook speed value (vanilla value = 200)
  default_cook_speed: 300
  # [set_fire_on_burn_probability] value between (0.1 , 1) .  -1 to disable
  set_fire_on_burn_probability: -1
  set_fire_range: 5
  fire_duration: 5
  custom_cook_speed:
    - 'IRON_ORE,800'
    - 'GOLD_ORE,1200'
    - 'DIAMOND_ORE,3500'
    - 'ANCIENT_DEBRIS,5000'
  exp_multiplier: 5
  result_multiplier:
    - 'IRON_INGOT,5'
    - 'GOLD_INGOT,5'
    - 'DIAMOND,4'
    - 'NETHERITE_SCRAP,4'


strings:
  prefix: "&8[&l&6En&4F&r&8]&r"

  furnace_added: "Fornace aggiunta correttamente [&e{0}&r]"
  furnace_removed: "Fornace rimossa correttamente [&e{0}&r]"
  success_reload: "File di configurazione ricaricato "

  #ERROR MESSAGES
  err_not_enf: "&cLa fornace indicata non e' una EnhancedFurnace"
  err_is_enf: "&cLa fornace indicata e' già una EnhancedFurnace"
  err_block_not_found: "&cNessun blocco fornace trovato"

  #COMMAND DESCRIPTION
  add_command: "&aRende la fornace targhettata una EnhancedFurnace"
  remove_command: "&aRipristina la fornace targhettata al suo stato classico"
  reload_command: "&aRicarica il file di configurazione"

  #LOG
  enf_break: "Enhanced furnace removed at [&e{0}&r] by &e{1}&r"



